# Generated by Django 2.2 on 2019-05-07 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_specializare'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimbaPredare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denr', models.CharField(max_length=8)),
                ('specializare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Specializare')),
            ],
        ),
    ]
