# Generated by Django 2.2 on 2019-05-07 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_limbapredare'),
    ]

    operations = [
        migrations.CreateModel(
            name='An',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denr', models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III')])),
                ('limba_predare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.LimbaPredare')),
            ],
        ),
    ]
