# Generated by Django 2.2 on 2019-05-08 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_grupa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universitate', models.CharField(default='Universitatea Babeș-Bolyai', editable=False, max_length=26)),
                ('facultate', models.CharField(default='Facultatea de Matematică și Informatică', editable=False, max_length=39)),
                ('an', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.An')),
                ('grupa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Grupa')),
                ('limba_predare', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.LimbaPredare')),
                ('specializare', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Specializare')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
