# Generated by Django 2.2 on 2019-05-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190521_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='an',
            name='limba_predare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ani', to='accounts.LimbaPredare'),
        ),
        migrations.AlterField(
            model_name='grupa',
            name='an',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupe', to='accounts.An'),
        ),
    ]
