# Generated by Django 2.2 on 2019-05-27 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0017_auto_20190527_2047'),
        ('accounts', '0009_auto_20190521_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activitate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('disciplina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cal.Repart')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activitati', to='accounts.Profil')),
            ],
        ),
    ]
