# Generated by Django 2.2 on 2019-05-29 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_activitate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitate',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Repart'),
        ),
    ]
