# Generated by Django 2.2 on 2019-05-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catedra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cladire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denr', models.CharField(max_length=40)),
                ('descriere', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(default='', max_length=10)),
                ('denr', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Formatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('an', models.IntegerField()),
                ('cod', models.CharField(max_length=10)),
                ('denumire', models.CharField(blank=True, max_length=20)),
                ('nivel', models.IntegerField()),
                ('componenta', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(default='', max_length=20)),
                ('denr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=3)),
                ('denr', models.CharField(max_length=8)),
            ],
        ),
    ]
