# Generated by Django 2.2 on 2019-05-08 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=10)),
                ('legenda', models.CharField(default='', max_length=80)),
                ('cladire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Cladire')),
            ],
        ),
        migrations.CreateModel(
            name='Cadru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=30)),
                ('web', models.CharField(blank=True, default='', max_length=50)),
                ('activ', models.IntegerField(default=1)),
                ('cod', models.CharField(max_length=5)),
                ('catedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Catedra')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Post')),
            ],
        ),
    ]
