# Generated by Django 2.2 on 2019-05-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_cadru_sala'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar', models.IntegerField(choices=[(1, 'I'), (2, 'II')])),
                ('tip_an', models.CharField(blank=True, choices=[('NT', 'Neterminal'), ('T', 'Terminal')], default='NT', max_length=10)),
                ('numar_saptamani', models.IntegerField(choices=[(14, '14 săptămâni'), (12, '12 săptămâni')], default=14)),
                ('data_inceput', models.DateField()),
                ('data_sfarsit', models.DateField()),
            ],
        ),
    ]
