# Generated by Django 2.2 on 2019-05-08 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_semestru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zi',
            name='cod',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Repart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_activitate', models.CharField(choices=[('C', 'Curs'), ('L', 'Laborator'), ('S', 'Seminar')], max_length=1)),
                ('nr_ore', models.IntegerField(blank=True)),
                ('ora_i', models.IntegerField()),
                ('ora_s', models.IntegerField()),
                ('cadru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Cadru')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Disciplina')),
                ('formatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Formatie')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Sala')),
                ('semestru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Semestru')),
                ('zi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Zi')),
            ],
        ),
    ]
