# Generated by Django 2.2 on 2019-05-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_auto_20190508_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='repart',
            name='frecventa',
            field=models.IntegerField(choices=[(0, 'saptamanal'), (1, 'saptamana 1'), (2, 'saptamana 2')], default=0),
        ),
        migrations.AlterField(
            model_name='repart',
            name='tip_activitate',
            field=models.CharField(choices=[('S', 'Seminar'), ('C', 'Curs'), ('L', 'Laborator')], max_length=1),
        ),
    ]
