# Generated by Django 2.2 on 2019-05-23 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0008_auto_20190521_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repart',
            name='tip_activitate',
            field=models.CharField(choices=[('S', 'Seminar'), ('C', 'Curs'), ('L', 'Laborator')], max_length=1),
        ),
        migrations.CreateModel(
            name='ActivitateNedidactica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inceput', models.DateField()),
                ('data_sfarsit', models.DateField()),
                ('descriere', models.CharField(max_length=50)),
                ('semestru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Semestru')),
            ],
        ),
    ]
