# Generated by Django 2.2 on 2019-05-23 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0009_auto_20190523_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repart',
            name='tip_activitate',
            field=models.CharField(choices=[('C', 'Curs'), ('S', 'Seminar'), ('L', 'Laborator')], max_length=1),
        ),
        migrations.CreateModel(
            name='StructuraSemestru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriere', models.CharField(max_length=100)),
                ('semestru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Semestru')),
            ],
        ),
    ]
