# Generated by Django 2.2 on 2019-05-23 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0010_auto_20190523_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitatenedidactica',
            name='semestru',
        ),
        migrations.AddField(
            model_name='activitatenedidactica',
            name='structura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cal.StructuraSemestru'),
        ),
        migrations.AlterField(
            model_name='repart',
            name='tip_activitate',
            field=models.CharField(choices=[('C', 'Curs'), ('L', 'Laborator'), ('S', 'Seminar')], max_length=1),
        ),
    ]
