# Generated by Django 2.2 on 2019-05-23 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0012_auto_20190523_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repart',
            name='tip_activitate',
            field=models.CharField(choices=[('L', 'Laborator'), ('S', 'Seminar'), ('C', 'Curs')], max_length=1),
        ),
        migrations.AlterField(
            model_name='structurasemestru',
            name='semestru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structuri_semstru', to='cal.Semestru'),
        ),
    ]
