# Generated by Django 2.2 on 2019-05-23 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0013_auto_20190523_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structurasemestru',
            name='semestru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structuri_semestru', to='cal.Semestru'),
        ),
    ]
