# Generated by Django 2.2 on 2019-05-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0015_auto_20190523_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitatenedidactica',
            name='structura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activitati_nedidactice', to='cal.StructuraSemestru'),
        ),
        migrations.AlterField(
            model_name='repart',
            name='tip_activitate',
            field=models.CharField(choices=[('L', 'Laborator'), ('S', 'Seminar'), ('C', 'Curs')], max_length=1),
        ),
    ]
